# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\"7\n\x12TransactionRequest\x12\x11\n\tid_barang\x18\x01 \x01(\x05\x12\x0e\n\x06jumlah\x18\x02 \x01(\x05\"\\\n\x13TransactionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0btotal_harga\x18\x03 \x01(\x05\x12\x0e\n\x06\x64iskon\x18\x04 \x01(\x05\">\n\x11StokUpdateRequest\x12\x11\n\tid_barang\x18\x01 \x01(\x05\x12\x16\n\x0ejumlah_terjual\x18\x02 \x01(\x05\"6\n\x12StokUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0eLaporanRequest\x12\x0f\n\x07periode\x18\x01 \x01(\t\"\"\n\x0fLaporanResponse\x12\x0f\n\x07laporan\x18\x01 \x03(\t\":\n\x0e\x41\x64\x64StokRequest\x12\x11\n\tid_barang\x18\x01 \x01(\x05\x12\x15\n\rjumlah_tambah\x18\x02 \x01(\x05\"3\n\x0f\x41\x64\x64StokResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xdc\x01\n\x07\x42\x61\x63kend\x12J\n\x0fProsesTransaksi\x12\x1a.common.TransactionRequest\x1a\x1b.common.TransactionResponse\x12\x44\n\x0bKirimKeStok\x12\x19.common.StokUpdateRequest\x1a\x1a.common.StokUpdateResponse\x12?\n\x0c\x41mbilLaporan\x12\x16.common.LaporanRequest\x1a\x17.common.LaporanResponse2\x8d\x01\n\nStokBarang\x12\x43\n\nUpdateStok\x12\x19.common.StokUpdateRequest\x1a\x1a.common.StokUpdateResponse\x12:\n\x07\x41\x64\x64Stok\x12\x16.common.AddStokRequest\x1a\x17.common.AddStokResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=24
  _globals['_TRANSACTIONREQUEST']._serialized_end=79
  _globals['_TRANSACTIONRESPONSE']._serialized_start=81
  _globals['_TRANSACTIONRESPONSE']._serialized_end=173
  _globals['_STOKUPDATEREQUEST']._serialized_start=175
  _globals['_STOKUPDATEREQUEST']._serialized_end=237
  _globals['_STOKUPDATERESPONSE']._serialized_start=239
  _globals['_STOKUPDATERESPONSE']._serialized_end=293
  _globals['_LAPORANREQUEST']._serialized_start=295
  _globals['_LAPORANREQUEST']._serialized_end=328
  _globals['_LAPORANRESPONSE']._serialized_start=330
  _globals['_LAPORANRESPONSE']._serialized_end=364
  _globals['_ADDSTOKREQUEST']._serialized_start=366
  _globals['_ADDSTOKREQUEST']._serialized_end=424
  _globals['_ADDSTOKRESPONSE']._serialized_start=426
  _globals['_ADDSTOKRESPONSE']._serialized_end=477
  _globals['_BACKEND']._serialized_start=480
  _globals['_BACKEND']._serialized_end=700
  _globals['_STOKBARANG']._serialized_start=703
  _globals['_STOKBARANG']._serialized_end=844
# @@protoc_insertion_point(module_scope)
